import { Box, Center, ColorModeScript } from "@chakra-ui/react";
import { ReactJSXElement } from "@emotion/react/types/jsx-namespace";
import Head from "next/head";
import React from "react";
import { Header } from "./Header/Header";
import theme from "./theme";

type Input = {
  title: string;
  children?: ReactJSXElement;
};
export const Layout = ({ title, children }: Input) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box height="100vh">
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <Header />
        <Center
          height="calc(100% - 60px)"
          width="100%"
          background="brand.backgroundcolor2"
        >
          {children}
        </Center>
        
      </Box>
    </>
  );
};
