import {
  Box,
  Center,
  ColorModeScript,
  useColorModeValue,
} from "@chakra-ui/react";
import {
  ReactJSXElement,
  ReactJSXElementChildrenAttribute,
} from "@emotion/react/types/jsx-namespace";
import Head from "next/head";
import React, { ReactNode } from "react";
import theme from "../theme";
import { Header } from "./Header/Header";

type Input = {
  title: string;
  children?: ReactNode;
};
export const Layout = ({ title, children }: Input) => {
  const bg = useColorModeValue("brand.backgroundcolor2", "gray.700");

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box height="100vh">
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <Header />
        <Center height="calc(100% - 60px)" width="100%" background={bg}>
          {children}
        </Center>
      </Box>
    </>
  );
};
